# thanks @tgrrtt https://gist.github.com/tgrrtt/96b206c22b82f92ce563
sudo: required

# specify language
language: node_js

node_js: "4"

# configure which branches to run
branches:
  # whitelist
  only:
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - dontrunme
    - test

before_script:
  - npm install -g gulp
script: gulp

## begin build steps
####################

before_install:
- sudo apt-get update -qq

install:

after_success:
- test $TRAVIS_PULL_REQUEST = false \
  && git push
